---
name: Tamás
surname: Nagy
position: "Assistant Professor"
address: "Institute of Psychololgy, ELTE Eötvös Loránd University"
phone: +36 30 627 6313
profilepic: mariecurie.jpg
www: nagytamas.netlify.app
email: nagytamas.hungary@gmail.com
twitter: nagyt
github: nthun
linkedin: tamas-nagy-phd-549bbb42
date: "`r format(Sys.time(), '%Y %B')`"
aboutme: "Tamás Nagy is an assistant professor of psychology at ELTE Eötvös Loránd University, Budapest. His research interests include stress and emotion psychophysiology, the application of machine learning and computational science in psychological research, and improving psychological science. He has been teaching data analysis and statistical inference for psychology students on B.A., M.A., and Ph.D. levels. He teaches courses in advanced research methodology, statistics, and R programming. He leads the ELTE Stress and Emotions Lab, which uses experimental methods and psychophysiology to uncover how we perceive physiological arousal, and how it affects our emotions, cognition, and behavior."
orcid: 0000-0001-5244-0356
scholar: Lec9WuYAAAAJ
output: vitae::twentyseconds
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(tinytex.verbose = TRUE)
library(vitae)
library(tidyverse)
library(lubridate)

```

# Research interests

- Stress and emotion physiology
- Machine learning and computational science
- Improving psychological science

# Education

```{r}

tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Ph.D. in Psychology", "2010-2015", "ELTE Eötvös Loránd University (and partly the University of Amsterdam)", "Budapest, Hungary",
  "M.A. in Psychology", "2001-2006", "ELTE Eötvös Loránd University", "Budapest, Hungary"
)  |> 
  detailed_entries(Degree, Year, Institution, Where, .protect = TRUE)
```


# Publications

```{r}

bibliography_entries(here::here("publications.bib")) %>%
  mutate(year = as_date(issued) |> year()) |>
  arrange(rev(year))
```






